import { Question, SectionId } from './types';

export const YES_NO_OPTIONS = ['Yes', 'No', 'Not sure'];

export const SECTIONS_MAP: Record<SectionId, { title: string; questions: Question[]; description?: string }> = {
  [SectionId.INTRO]: {
    title: 'Introduction',
    questions: [],
  },
  [SectionId.PERSONAL_HISTORY]: {
    title: 'AMDP Personal History',
    description: 'Please complete the following background information.',
    questions: [
      {
        id: 'ph_1',
        text: '1. Gender',
        type: 'single-select',
        options: ['Male', 'Female', 'Other'],
      },
      {
        id: 'ph_2',
        text: '2. Date of birth',
        type: 'date',
        subText: 'DD.MM.YYYY',
      },
      {
        id: 'ph_3',
        text: '3. Accommodation',
        type: 'single-select',
        options: [
          'Not ascertained',
          'Assisted living',
          'Independent living',
          'Living with parents/relatives',
          'Institutional care (e.g., home/hospital)',
          'Other (e.g., emergency accommodation)',
        ],
      },
      {
        id: 'ph_4',
        text: '4. Living arrangements',
        subText: 'Select all that apply',
        type: 'multi-select',
        options: [
          'Not ascertained',
          'Living alone',
          'With spouse/partner',
          'With parent(s)',
          'With child/children',
          'Other (e.g., with friends)',
        ],
      },
      {
        id: 'ph_5',
        text: '5. Education',
        subText: 'Highest educational school leaving qualification achieved',
        type: 'single-select',
        options: [
          'Not ascertained',
          'School for special needs',
          'No leaving qualification',
          'School leaving qualification below GCSE',
          'GCSE or equivalent',
          'GCE/A level',
          'University degree',
        ],
      },
      {
        id: 'ph_6',
        text: '6. Employment',
        type: 'single-select',
        options: [
          'Not ascertained',
          'In-training/re-training',
          'Nonmanual employee',
          'Manual/skilled employee',
          'Self-employed',
          'Retired',
          'Unemployed',
          'Housemaker',
          'Other',
        ],
      },
      {
        id: 'ph_7',
        text: '7. Examination setting',
        type: 'single-select',
        options: [
          'Out-patient',
          'In-patient',
          'Day patient',
          'Other',
        ],
      },
      {
        id: 'ph_8',
        text: '8. Reason for referral',
        type: 'single-select',
        options: [
          'Treatment',
          'Assessment',
          'Consultation',
          'Other assessment',
        ],
      },
      {
        id: 'ph_9',
        text: '9. Course of illness',
        type: 'single-select',
        options: [
          'Not ascertained',
          'First episode',
          'Repeat/persistent episode',
        ],
      },
      {
        id: 'ph_10',
        text: '10. Mental health problems in the family',
        type: 'yes-no',
        options: ['Yes', 'No'],
      },
      {
        id: 'ph_11',
        text: '11. Severity of illness (CGI)',
        subText: 'Self-rated estimation based on Clinical Global Impressions scale',
        type: 'single-select',
        options: [
          'Not ascertained',
          'Not ill',
          'Borderline mentally ill',
          'Mildly ill',
          'Moderately ill',
          'Markedly ill',
          'Severely ill',
          'Extremely ill',
        ],
      },
      {
        id: 'ph_12',
        text: '12. Diagnoses',
        subText: 'List any known psychiatric or somatic diagnoses',
        type: 'text',
        placeholder: 'e.g., Depression, Hypertension...',
      },
    ],
  },
  [SectionId.SAFETY]: {
    title: 'Section 0 — Safety',
    questions: [
      {
        id: 's0_1',
        text: 'Are you in immediate danger right now, or thinking of harming yourself or someone else?',
        type: 'yes-no',
        options: ['Yes', 'No'],
      },
      {
        id: 's0_2',
        text: 'Right now, are you experiencing things that make reality feel unclear (for example, hearing/seeing things others don’t, or very strong unusual beliefs)?',
        type: 'yes-no',
        options: YES_NO_OPTIONS,
      },
    ],
  },
  [SectionId.CORE]: {
    title: 'Section 1 — Core',
    questions: [
      {
        id: 'c1',
        text: 'Which best matches the pattern of your main difficulty lately?',
        type: 'single-select',
        options: [
          'It’s there most days (steady baseline)',
          'It comes in distinct episodes lasting days–weeks',
          'It comes in sudden spikes that peak within minutes–hours',
          'It’s mostly triggered by specific cues (places/people/memories/sensations)',
          'It varies a lot / not sure',
        ],
      },
      {
        id: 'c2',
        text: 'Which areas are most affected? (Pick up to 3)',
        type: 'multi-select',
        options: [
          'Mood / interest',
          'Worry / tension',
          'Panic / body alarms',
          'Trauma reminders',
          'Intrusive thoughts / rituals',
          'Attention / organization',
          'Sleep / circadian rhythm',
          'Eating / body image',
          'Physical symptoms / health worries',
          'Alcohol / drugs',
          'Relationships / intense conflict',
          'Feeling unreal / detached',
          'Unusual experiences / perception changes',
          'Other / not sure',
        ],
      },
      {
        id: 'c3',
        text: 'How much is this affecting your daily functioning (work/school/home/social)? (0–10)',
        type: 'scale',
        min: 0,
        max: 10,
        subText: '0 (not at all) … 10 (severely)',
      },
    ],
  },
  [SectionId.PANIC]: {
    title: 'Section P — Panic / Body alarm surges',
    questions: [
      { id: 'p1', text: 'When a surge happens, does it peak within about 10 minutes?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'p2', text: 'During surges, do you fear something catastrophic (for example: dying, fainting, losing control, or “going crazy”)?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'p3', text: 'During surges, which sensations do you notice?', type: 'multi-select', options: ['Heart racing / pounding', 'Shortness of breath', 'Feeling of choking', 'Chest tightness / pain', 'Dizziness / lightheaded', 'Trembling / shaking', 'Sweating', 'Nausea / stomach upset', 'Tingling / numbness', 'Hot/cold flashes', 'Feeling unreal / detached', 'Fear of dying', 'Fear of losing control'] },
      { id: 'p4', text: 'How often have these surges happened in the last month?', type: 'single-select', options: ['0', '1', '2–3', 'About weekly', 'More than weekly', 'Not sure'] },
      { id: 'p5', text: 'Do you spend a lot of time worrying about having another surge?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'p6', text: 'Have you changed your behavior because of these surges (avoiding places, needing an exit, carrying “just in case” items)?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'p7', text: 'Do these surges mainly happen after caffeine/stimulants/alcohol/drugs, medication changes, or during withdrawal?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.INTRUSIONS]: {
    title: 'Section O — Intrusions / compulsions / control loop',
    questions: [
      { id: 'o1', text: 'Do you get unwanted intrusive thoughts/images/urges that feel disturbing or against your values?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o2', text: 'Do you do repeated behaviors or mental rituals to reduce anxiety or prevent something bad?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o3', text: 'About how much time per day do these thoughts/behaviors take?', type: 'single-select', options: ['<30 min', '30–60 min', '1–3 hours', '3–8 hours', '>8 hours', 'Not sure'] },
      { id: 'o4', text: 'After you do the ritual, do you get temporary relief that doesn’t last (the urge/worry returns)?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o5', text: 'Which themes fit best?', type: 'multi-select', options: ['Germs/contamination', 'Harm to self/others', 'Mistakes/checking', 'Symmetry/“just right”', 'Taboo/religious/sexual thoughts', 'Relationship doubts', 'Health fears/body checking', 'Other/not sure'] },
      { id: 'o6', text: 'Do you avoid situations because of these thoughts/urges?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o7', text: 'Do you repeatedly seek reassurance from others to feel certain or safe?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o8', text: 'Do you recognize (at least sometimes) that the fear/need is exaggerated or doesn’t fully make sense?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'o9', text: 'How much do these thoughts/rituals interfere with your daily life?', type: 'single-select', options: ['Not at all', 'A little', 'Moderately', 'Severely'] },
    ],
  },
  [SectionId.TRAUMA]: {
    title: 'Section T — Trauma / cue reactivity',
    questions: [
      { id: 't1', text: 'Have you experienced or witnessed something that felt life-threatening, sexually violating, or extremely frightening?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 't2', text: 'Do you have unwanted memories/flashbacks/nightmares about it?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 't3', text: 'Do you avoid reminders (places, people, conversations, thoughts) related to it?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 't4', text: 'Do you feel on edge, jumpy, or hyperalert much of the time?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 't5', text: 'How long have these reactions lasted?', type: 'single-select', options: ['<1 month', '1–3 months', '3–12 months', '>1 year', 'Not sure'] },
      { id: 't6', text: 'Do any of these fit?', type: 'multi-select', options: ['Feeling numb or emotionally shut down', 'Strong self-blame or guilt', 'Belief the world is unsafe', 'Detached/unreal feelings', 'Irritable or angry outbursts', 'Sleep disturbance', 'None of these'] },
    ],
  },
  [SectionId.WORRY]: {
    title: 'Section W — Worry loop / tension',
    questions: [
      { id: 'w1', text: 'Do you worry about many different topics (health, money, family, work), more days than not?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'w2', text: 'When you start worrying, can you stop, or does it keep going?', type: 'single-select', options: ['I can stop fairly easily', 'It’s hard to stop', 'I can’t stop once it starts', 'Not sure'] },
      { id: 'w3', text: 'Do you experience these symptoms alongside the worry? (Select all that apply)', type: 'multi-select', options: ['Restlessness / feeling keyed up or on edge', 'Being easily fatigued', 'Difficulty concentrating / mind going blank', 'Irritability', 'Muscle tension', 'Sleep disturbance (difficulty falling/staying asleep, or restless sleep)'] },
      { id: 'w4', text: 'Is the worry mainly about being judged, embarrassed, or rejected by others?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.EXECUTIVE]: {
    title: 'Section E — Executive control / attention',
    questions: [
      { id: 'e1', text: 'Do you often make careless mistakes or miss details?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e2', text: 'Is it hard to stay focused on reading or conversations?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e3', text: 'Do you lose things or forget appointments frequently?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e4', text: 'Do you start tasks late or can’t get started unless it’s urgent or interesting?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e5', text: 'Do you interrupt or act impulsively more than you’d like?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e_hyper', text: 'Do you often fidget, feel unable to sit still, or feel like you are "driven by a motor"?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'e6', text: 'Were these patterns present before age 12 and in more than one setting (home/school/work)?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.MOOD]: {
    title: 'Section M — Mood shutdown / low reward',
    questions: [
      { id: 'm1', text: 'In the last 2 weeks, have you felt down/sad/empty most days?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'm2', text: 'In the last 2 weeks, have you lost interest/pleasure in most things?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'm_symptoms', text: 'Have you experienced these changes nearly every day? (Select all that apply)', type: 'multi-select', options: ['Significant weight loss/gain or appetite change', 'Sleep disturbance (insomnia or sleeping too much)', 'Psychomotor agitation (restless) or retardation (slowed down)', 'Fatigue or loss of energy', 'Feelings of worthlessness or excessive guilt', 'Diminished ability to think or concentrate'] },
      { id: 'm3', text: 'How long has this current low/shutdown period lasted?', type: 'single-select', options: ['<1 week', '1–2 weeks', '2–4 weeks', '>1 month', '>6 months', 'Not sure'] },
      { id: 'm4', text: 'During this period, how much has it interfered with daily life?', type: 'single-select', options: ['Not at all', 'A little', 'Moderately', 'Severely'] },
      { id: 'm6', text: 'In the last 2 weeks, have you had thoughts that life isn’t worth living?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.ACTIVATION]: {
    title: 'Section A — Activation / drive shift',
    questions: [
      { id: 'a1', text: 'Have there been periods of 4+ days where you felt unusually energized, driven, or irritable compared to your normal?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'a2', text: 'During those periods, which of these did you experience? (Select all that apply)', type: 'multi-select', options: ['Decreased need for sleep (felt rested after only a few hours)', 'More talkative than usual / pressure to keep talking', 'Flight of ideas / racing thoughts', 'Distractibility', 'Increase in goal-directed activity (social, work, sexual) or psychomotor agitation', 'Excessive involvement in risky activities (buying sprees, sexual indiscretions, foolish investments)', 'Inflated self-esteem or grandiosity'] },
      { id: 'a5', text: 'Did these periods cause problems (work, relationships) or did others seem concerned?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'a6', text: 'At other times, do you have low/shutdown periods that last days to weeks?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.REALITY]: {
    title: 'Section R — Reality testing / unusual experiences',
    questions: [
      { id: 'r1', text: 'Have you heard voices when no one was there?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'r2', text: 'Have you felt people were watching, plotting, or trying to harm you without clear evidence?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'r3', text: 'Have you believed you had special powers or a special mission that others strongly disagreed with?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'r4', text: 'Have you had trouble organizing your thoughts/speech so others couldn’t follow?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'r5', text: 'Have you felt emotionally flat or unmotivated for long periods?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 'r6', text: 'Did these experiences mainly occur during heavy substance use or withdrawal, or after a medical event?', type: 'yes-no', options: YES_NO_OPTIONS },
    ],
  },
  [SectionId.SUBSTANCE]: {
    title: 'Section S — Substance pattern',
    questions: [
      { id: 's1', text: 'In the last 12 months, have you used alcohol/drugs more than you intended?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 's2', text: 'Have you tried to cut down but couldn’t?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 's3', text: 'Do you crave or feel strong urges to use?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 's4', text: 'Have you continued using despite causing problems (health, work, relationships)?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 's5', text: 'Do you get withdrawal symptoms when stopping or reducing?', type: 'yes-no', options: YES_NO_OPTIONS },
      { id: 's6', text: 'Which substances have been involved?', type: 'multi-select', options: ['Alcohol', 'Cannabis', 'Stimulants', 'Sedatives', 'Opioids', 'Psychedelics', 'Nicotine', 'Other/not sure'] },
    ],
  },
  [SectionId.RESULTS]: { title: 'Results', questions: [] },
  [SectionId.EMERGENCY]: { title: 'Emergency Stop', questions: [] },
};